name: Deploy to InfinityFree FTP

on:
  push:
    paths-ignore:
      - 'riyo_app/**'
      - '.github/workflows/build_app.yml'
      - '.github/workflows/test_and_build.yml'
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy Web Application via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files via FTP
        uses: SamKirkland/ftp-deploy-action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_41358970
          password: 6jhD3qCvd1eX8y
          port: 21
          server-dir: 'htdocs/'
          exclude: |
            **/.git*
            **/.git*/**
            riyo_app/**
            .github/**
